### ISSUE TITLE
Get keywords from imenu?

### ISSUE THREAD

**Issue by alphapapa** [tj64/navi#6]
Hi Thorsten,

Just curious, have you thought about getting language keywords from `imenu` instead of hardcoding your own lists?  It seems like it could reduce the maintenance burden and also add support for more languages for free.  

I know you're probably not interested in doing this yourself, I'm just asking to see what you think, if maybe you had already tried, etc.  :)

Thanks.

**Comment by tj64** [comment]
Imenu works with outshine, but I did not consider it for Navi.
Would be another nice taks for a new maintainer ;-)

**Comment by alphapapa** [comment]
Consider it on my list.  ;)
